version: '3'
services:
    oracle:
        container_name: oracledb
        image: store/oracle/database-enterprise:12.2.0.1
        ports:
            - 1521:1521
            - 5500:5500
            - 5501:5501
            - 5502:5502
        volumes:
            - "./data/oracle:/ORCL"
        env_file:
            - ora.conf
        networks:
            - db
    restapi:
        image: restapi
        build: 
            dockerfile: Dockerfile
            context: ./restapi
        restart: always
        container_name: restapi
        ports:
            - 3000:3000
        env_file:
            - restapi/envfile.list
        networks:
            - db
    scraper:
        image: scraper
        build:
            dockerfile: Dockerfile
            context: ./scraper
        container_name: scraper
        networks:
            - db
    # webapp:
    #     image: webapp
    #     build:
    #         dockerfile: Dockerfile
    #         context: ./webapp
    #     restart: always
    #     container_name: webapp
    #     ports:
    #         - 8080:8080
    #     networks:
    #         - db
networks:
    db:
